-- The public storefront has a curated built-in catalog. This seed mirrors those
-- items in D1 so checkout, order records, and the admin catalog share one source
-- of truth without rendering duplicate cards in the shop.
INSERT OR IGNORE INTO marketplace_product_catalog
  (id, slug, title, category, price_cents, image_url, short_description, details_json, active, created_at, updated_at)
VALUES
  ('catalog-living-memorial-tree', 'living-memorial-tree', 'Living Memorial Tree', 'memorial-trees', 7900, 'https://www.woafmeow.com/senior-care-platform/media/products/memorial-tree.jpg', 'A region-matched sapling, engraved garden marker, and planting guide.', '["Climate-matched tree","Personalized garden marker","Planting and first-year care guide"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z'),
  ('catalog-photo-collar-memory-frame', 'photo-collar-memory-frame', 'Pet Portrait Memory Frame', 'picture-frames', 8200, 'https://www.woafmeow.com/senior-care-platform/media/products/memory-frames.jpg', 'A dimensional portrait frame made around one favorite pet photograph.', '["Photo and nameplate proof","Tabletop or wall hardware"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z'),
  ('catalog-portrait-name-pendant', 'portrait-name-pendant', 'Pet Photo Memory Locket', 'personalized-gifts', 6800, 'https://www.woafmeow.com/senior-care-platform/media/products/portrait-pendant.jpg', 'A small locket that keeps one pet photograph close.', '["Image and inscription proof","Chain and care cloth"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z'),
  ('catalog-hand-thrown-ceramic-urn', 'hand-thrown-ceramic-urn', 'Pawprint Bio Pet Urn', 'urns', 14800, 'https://www.woafmeow.com/senior-care-platform/media/products/ceramic-urn.jpg', 'A quiet bio-material vessel with a natural wood lid and paw relief.', '["Three capacities","Capacity and inscription confirmation"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z'),
  ('catalog-portrait-signet-ring', 'portrait-signet-ring', 'Two Hearts Keepsake Ring', 'engraved-jewelry', 9400, 'https://www.woafmeow.com/senior-care-platform/media/products/signet-ring.jpg', 'Two linked hearts with a pet name or date engraved inside the band.', '["Printable sizing guide","Inscription proof"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z'),
  ('catalog-paw-print-bracelet', 'paw-print-bracelet', 'Linked Memory Bracelet', 'engraved-jewelry', 5800, 'https://www.woafmeow.com/senior-care-platform/media/products/paw-bracelet.jpg', 'Four linked circles with a pet name or date on one polished link.', '["One engraved link","Toggle closure","Inscription proof"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z'),
  ('catalog-custom-portrait-miniature', 'custom-portrait-miniature', 'Custom Portrait Miniature', '3d-keepsakes', 12900, 'https://www.woafmeow.com/senior-care-platform/media/products/portrait-figure.jpg', 'A hand-finished miniature built from photographs of your pet.', '["Digital sculpture preview","Markings and color proof"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z'),
  ('catalog-custom-plush-portrait', 'custom-plush-portrait', 'Custom Plush Portrait', 'plush-replicas', 17900, 'https://www.woafmeow.com/senior-care-platform/media/products/plush-portrait.jpg', 'A soft companion designed around coat pattern, ears, tail, and posture.', '["Photo checklist","Coat and markings map","Personalized name tag"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z'),
  ('catalog-senior-pet-home-comfort-consult', 'senior-pet-home-comfort-consult', 'Senior-Pet Home Comfort Consult', 'aging-pet-services', 9500, 'https://www.woafmeow.com/senior-care-platform/media/real/photo-54.jpg', 'A room-by-room review of routes, rest areas, bowls, litter boxes, and steps.', '["45-minute video visit","Three ranked changes to discuss with your veterinary team"]', 1, '2026-08-08T00:00:00.000Z', '2026-08-08T00:00:00.000Z');
